// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjT_va6HYpNB-cg8Iux-NdQUxfJF0_icA',
    appId: '1:605002599336:web:69b381f34d309fc32c2b9d',
    messagingSenderId: '605002599336',
    projectId: 'com-cipherschools-assign-72ccf',
    authDomain: 'com-cipherschools-assign-72ccf.firebaseapp.com',
    storageBucket: 'com-cipherschools-assign-72ccf.firebasestorage.app',
    measurementId: 'G-KR1V1WEDJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9MehDAru6RED-EQoerKqDYsEtBiXum8',
    appId: '1:605002599336:android:7e5eadbe0e0ffef52c2b9d',
    messagingSenderId: '605002599336',
    projectId: 'com-cipherschools-assign-72ccf',
    storageBucket: 'com-cipherschools-assign-72ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4mU72k4GBbXnl3EoRkW6qiXNTYRvDv0',
    appId: '1:605002599336:ios:1f15b17f6aaa3ef02c2b9d',
    messagingSenderId: '605002599336',
    projectId: 'com-cipherschools-assign-72ccf',
    storageBucket: 'com-cipherschools-assign-72ccf.firebasestorage.app',
    iosBundleId: 'com.example.cipherschoolAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4mU72k4GBbXnl3EoRkW6qiXNTYRvDv0',
    appId: '1:605002599336:ios:1f15b17f6aaa3ef02c2b9d',
    messagingSenderId: '605002599336',
    projectId: 'com-cipherschools-assign-72ccf',
    storageBucket: 'com-cipherschools-assign-72ccf.firebasestorage.app',
    iosBundleId: 'com.example.cipherschoolAssignment',
  );
}
